// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw4zJobGvxNT7bRwdJyWCU4TGfpCFfXUc',
    appId: '1:215256200314:web:077b078b1c0e8e673cb7c3',
    messagingSenderId: '215256200314',
    projectId: 'instagram-599a7',
    authDomain: 'instagram-599a7.firebaseapp.com',
    storageBucket: 'instagram-599a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjdhPiTQhHflKL3MRxDNyLko1xG2MR-X4',
    appId: '1:215256200314:android:06bf11001ca8a4c33cb7c3',
    messagingSenderId: '215256200314',
    projectId: 'instagram-599a7',
    storageBucket: 'instagram-599a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjbMNqeZPTZ6-yszbtvqSzZz-ygpoQTaI',
    appId: '1:215256200314:ios:1a86cea47f35a2fb3cb7c3',
    messagingSenderId: '215256200314',
    projectId: 'instagram-599a7',
    storageBucket: 'instagram-599a7.firebasestorage.app',
    iosClientId: '215256200314-mkfg7ub3r9d4e85smk1l98uaep369379.apps.googleusercontent.com',
    iosBundleId: 'com.example.importantPlacesExplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjbMNqeZPTZ6-yszbtvqSzZz-ygpoQTaI',
    appId: '1:215256200314:ios:1a86cea47f35a2fb3cb7c3',
    messagingSenderId: '215256200314',
    projectId: 'instagram-599a7',
    storageBucket: 'instagram-599a7.firebasestorage.app',
    iosClientId: '215256200314-mkfg7ub3r9d4e85smk1l98uaep369379.apps.googleusercontent.com',
    iosBundleId: 'com.example.importantPlacesExplorer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw4zJobGvxNT7bRwdJyWCU4TGfpCFfXUc',
    appId: '1:215256200314:web:a1709648801d62cb3cb7c3',
    messagingSenderId: '215256200314',
    projectId: 'instagram-599a7',
    authDomain: 'instagram-599a7.firebaseapp.com',
    storageBucket: 'instagram-599a7.firebasestorage.app',
  );
}
